name: ShadowXP
version: 3.1
main: com.MikeTheShadow.ShadowXP.ShadowXP
api-version: 1.13
authors: [MikeTheShadow]
description: Modifies the XP leveling system to create a unique leveling system
depend: [WorldGuard,XPBoost,Vault,Duels]
commands:
  userstats:
    description: Gets yours/a users current stats.
    usage: /<checkstats> [player]
    permission: ShadowXP.misc
    permission-message: You don't have ShadowXP.misc permission
  mystats:
    description: Gets your current stats.
    usage: /<mystats>
    permission: ShadowXP.basic
    permission-message: You don't have ShadowXP.basic permission
  fixexperience:
    description: Updates all current players experience to match that of the leveling system.
    usage: /<fixexperience>
    permission: ShadowXP.admin
    permission-message: You don't have ShadowXP.admin permission
  setexperience:
    description: Sets the experience of a player.
    usage: /<setexperience> [player] [Amount]
    permission: ShadowXP.admin
    permission-message: You don't have ShadowXP.admin permission
  setlevel:
    description: Sets the level of a player.
    usage: /<setlevel> [player] [Amount]
    permission: ShadowXP.admin
    permission-message: You don't have ShadowXP.admin permission
  addexperience:
    description: Adds experience to the select player.
    usage: /<addexperience> [player] [Amount]
    permission: ShadowXP.admin
    permission-message: You don't have ShadowXP.admin permission